# yaml-language-server: $schema=./task2ci.schema.json
---
actions:
  checkout: actions/checkout@v4
  setup-task: go-task/setup-task@v2
  setup-task2ci: arnested/setup-task2ci@v1

tags:
  build:
    workflow: ci
    runs-on: ubuntu-latest

  test:
    workflow: ci
    runs-on: ubuntu-latest
