package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// placeholderRE matches `# @ci: <tag>` lines (any leading whitespace, anything
// after the tag is tolerated). The line including its trailing newline is the
// match, so empty substitutions cleanly remove the line.
var placeholderRE = regexp.MustCompile(`(?m)^([ \t]*)# @ci:[ \t]*(\S+).*$\n?`)

// Task is one Taskfile task slotted into CI via an @ci annotation.
type Task struct {
	Name string // task identifier (key in Taskfile tasks map)
	Step string // resolved display name: annotation override > desc > task name
	Run  string // run command, e.g. "task test" or "go tool task test"
}

// listTemplates returns paths to *.yaml and *.yml files under dir (sorted).
func listTemplates(dir string) ([]string, error) {
	var out []string
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading dir %s: %w", dir, err)
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if strings.HasSuffix(name, ".yaml") || strings.HasSuffix(name, ".yml") {
			out = append(out, filepath.Join(dir, name))
		}
	}
	sort.Strings(out)
	return out, nil
}

// outputPathFor maps `.task2ci/workflows/<base>.{yaml,yml}` to
// `.github/workflows/<base>.yaml`. Output is always .yaml.
func outputPathFor(tpath string) string {
	base := filepath.Base(tpath)
	base = strings.TrimSuffix(strings.TrimSuffix(base, ".yaml"), ".yml")
	return filepath.Join(OutputDir, base+".yaml")
}

// renderTemplate substitutes every `# @ci: <tag>` placeholder in data with the
// rendered step block for that tag. The autogenerated header is prepended.
// Returns the rendered bytes and the list of tags referenced (in source order,
// with duplicates).
func renderTemplate(tpath string, data []byte, tasksByTag map[string][]Task) ([]byte, []string, error) {
	var refs []string
	var renderErr error
	out := placeholderRE.ReplaceAllFunc(data, func(match []byte) []byte {
		if renderErr != nil {
			return match
		}
		sub := placeholderRE.FindSubmatch(match)
		indent := string(sub[1])
		tag := string(sub[2])
		refs = append(refs, tag)
		tasks := tasksByTag[tag]
		if len(tasks) == 0 {
			return nil
		}
		block, err := renderBlock(tasks, indent)
		if err != nil {
			renderErr = err
			return match
		}
		return []byte(block + "\n")
	})
	if renderErr != nil {
		return nil, refs, renderErr
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "# THIS FILE IS AUTOGENERATED by task2ci. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "# Source: %s\n", tpath)
	fmt.Fprintf(&buf, "# To change CI: edit the source template (or Taskfile.yaml), then run `task2ci`.\n")
	buf.Write(out)
	return stripTrailingWhitespace(buf.Bytes()), refs, nil
}

// renderBlock renders a series of steps at the given indent, with a blank line
// between consecutive steps.
func renderBlock(tasks []Task, indent string) (string, error) {
	parts := make([]string, len(tasks))
	for i, t := range tasks {
		s, err := renderStep(t, indent)
		if err != nil {
			return "", err
		}
		parts[i] = s
	}
	return strings.Join(parts, "\n\n"), nil
}

// renderStep encodes one step via yaml.v3 (so values are quoted correctly when
// needed) then re-indents and prefixes the first line with a "- ".
func renderStep(t Task, indent string) (string, error) {
	type stepFields struct {
		Name string `yaml:"name,omitempty"`
		Run  string `yaml:"run,omitempty"`
	}
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(stepFields{Name: t.Step, Run: t.Run}); err != nil {
		return "", fmt.Errorf("encoding step for task %q: %w", t.Name, err)
	}
	_ = enc.Close()

	lines := strings.Split(strings.TrimRight(buf.String(), "\n"), "\n")
	for i, line := range lines {
		if i == 0 {
			lines[i] = indent + "- " + line
		} else {
			lines[i] = indent + "  " + line
		}
	}
	return strings.Join(lines, "\n"), nil
}

// stripTrailingWhitespace removes trailing spaces/tabs from each line.
// Belt-and-suspenders for any tool that ever flags trailing whitespace.
func stripTrailingWhitespace(b []byte) []byte {
	lines := bytes.Split(b, []byte("\n"))
	for i, line := range lines {
		lines[i] = bytes.TrimRight(line, " \t")
	}
	return bytes.Join(lines, []byte("\n"))
}
